#!/usr/bin/env python3
"""
seeds.py — derive deterministic, reproducible variant seeds from quantum bytes.

Workflow:
  1. Fetch quantum bytes (see qrng.py — ANU real hardware by default).
  2. Derive a set of uint64 seeds, one per variation domain (arena layout,
     crowd, textures, props, lighting, graffiti).
  3. Store the raw quantum bytes + provenance alongside the seeds
     (SeedPack.save) so any variant can be regenerated byte-identically later.

Determinism: derive() is SHA-256(domain || label || quantum_bytes). Same
bytes + same label = same seed, every time, on any machine. The bytes are the
only source of entropy; no wall-clock, no process randomness.

Interop note: the JS generative tools (tools/generative/rng.js) take integer
seeds via mulberry32 — the uint64 seeds produced here can be passed straight
in (JS consumers should mask to 32 bits: seed >>> 0).
"""

import hashlib
import json
import os
import struct

from qrng import quantum_bytes


# ---------------------------------------------------------------------------
# Core derivation
# ---------------------------------------------------------------------------

def derive(qbytes, label):
    """Derive a uint64 seed for `label` from quantum bytes (deterministic)."""
    h = hashlib.sha256()
    h.update(b"ashlane-quantum-seed-v1:")
    h.update(label.encode("utf-8"))
    h.update(b":")
    h.update(qbytes)
    return struct.unpack(">Q", h.digest()[:8])[0]


def derive_many(qbytes, labels):
    """Derive a dict of label -> uint64 seed."""
    return {label: derive(qbytes, label) for label in labels}


# ---------------------------------------------------------------------------
# Domain seed sets
# ---------------------------------------------------------------------------

ARENA_LABELS = ["layout", "props", "textures", "lighting", "graffiti", "audio"]
CROWD_LABELS = ["section_a", "section_b", "section_c", "section_d",
                "section_e", "section_f", "variation"]
TEXTURE_LABELS = ["wall", "ground", "decal", "accent", "wear"]
PROP_LABELS = ["barrier", "trash", "signage", "vehicle", "fixture"]


def arena_seeds(qbytes):
    """Seeds for arena/worldgen layout variation."""
    return derive_many(qbytes, ARENA_LABELS)


def crowd_seeds(qbytes):
    """Seeds for crowd variation (per-section density/body/clothing)."""
    return derive_many(qbytes, CROWD_LABELS)


def texture_seeds(qbytes):
    """Seeds for texture/prop variation (walls, ground, decals, wear)."""
    return derive_many(qbytes, TEXTURE_LABELS)


def prop_seeds(qbytes):
    """Seeds for prop placement variation."""
    return derive_many(qbytes, PROP_LABELS)


def full_variant_pack(qbytes, provenance, name="variant"):
    """Build the complete, storable seed pack for one quantum pull."""
    return {
        "name": name,
        "quantum_bytes_hex": qbytes.hex(),
        "quantum_bytes_len": len(qbytes),
        "provenance": provenance,
        "arena": arena_seeds(qbytes),
        "crowd": crowd_seeds(qbytes),
        "textures": texture_seeds(qbytes),
        "props": prop_seeds(qbytes),
    }


# ---------------------------------------------------------------------------
# SeedPack: persistence (bytes + provenance travel with the seeds)
# ---------------------------------------------------------------------------

class SeedPack:
    """A reproducible variant: quantum bytes, provenance, and derived seeds.

    Save to JSON. To regenerate an identical variant, load the file and use
    the stored bytes — never re-fetch (quantum bytes are one-shot; the API
    will never give you the same bytes twice).
    """

    def __init__(self, qbytes, provenance, name="variant"):
        self.qbytes = qbytes
        self.provenance = provenance
        self.name = name
        self.pack = full_variant_pack(qbytes, provenance, name)

    @classmethod
    def new(cls, nbytes=64, sources=("anu",), name="variant",
            allow_classical_fallback=True):
        """Pull fresh quantum bytes and derive a new pack."""
        qbytes, provenance = quantum_bytes(
            nbytes, sources=sources,
            allow_classical_fallback=allow_classical_fallback)
        return cls(qbytes, provenance, name=name)

    @classmethod
    def load(cls, path):
        with open(path, "r", encoding="utf-8") as f:
            pack = json.load(f)
        qbytes = bytes.fromhex(pack["quantum_bytes_hex"])
        obj = cls(qbytes, pack["provenance"], name=pack.get("name", "variant"))
        obj.pack = pack  # keep stored derived seeds as-is
        return obj

    def save(self, path):
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.pack, f, indent=2)
        return path

    def verify(self):
        """Re-derive every seed from stored bytes; returns True if the
        pack is byte-identical to what the bytes produce (reproducible)."""
        fresh = full_variant_pack(self.qbytes, self.provenance, self.name)
        for domain in ("arena", "crowd", "textures", "props"):
            if fresh[domain] != self.pack[domain]:
                return False
        return True


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    pack = SeedPack.new(nbytes=64, name="selftest")
    print("name:", pack.name)
    print("bytes:", pack.qbytes.hex()[:64] + "...")
    print("provenance:", pack.provenance[:100] + "...")
    print("arena seeds:", pack.pack["arena"])
    # Determinism check: same bytes -> same seeds
    pack2 = SeedPack(pack.qbytes, pack.provenance, name="selftest")
    assert pack2.pack["arena"] == pack.pack["arena"], "non-deterministic!"
    assert pack.verify(), "verify() failed"
    print("determinism + verify(): OK")
