/**
 * ashlane-splat-loader.ts — Gaussian Splat loading for AshLane levels.
 *
 * Loads binary PLY splats (3DGS format) generated by
 * tools/generative/splat/mesh-to-splat.py and renders them as
 * camera-facing soft quads inside the game scene.
 *
 * Viewer reference: valentil/gaussian-splats (MIT). This loader is a
 * minimal AshLane-native implementation (no extra deps beyond three).
 * For large splats with LOD/compression, see reall3d-com/Reall3dViewer (MIT).
 *
 * Usage:
 *   import { loadSplat } from "./ashlane-splat-loader";
 *   const splat = await loadSplat("props/crate.ply"); // public/splats/
 *   splat.position.set(10, 0, 5);
 *   scene.add(splat);
 */
import * as THREE from "three";

const BASE = import.meta.env.BASE_URL || "/";
const SH_C0 = 0.28209479177387814;

interface ParsedSplat {
  count: number;
  positions: Float32Array;
  colors: Float32Array;
  scales: Float32Array;
}

/** Parse binary 3DGS PLY into typed arrays. */
export function parseSplatPLY(buf: ArrayBuffer): ParsedSplat {
  const bytes = new Uint8Array(buf);
  const headText = new TextDecoder().decode(bytes.slice(0, 4096));
  const endH = headText.indexOf("end_header");
  if (endH < 0) throw new Error("Not a PLY file (no end_header)");
  const header = headText.slice(0, endH);
  const dataStart = endH + "end_header".length + 1;
  const n = parseInt(header.match(/element vertex (\d+)/)![1], 10);
  const props = [...header.matchAll(/property float (\w+)/g)].map((m) => m[1]);
  const stride = props.length * 4;
  const dv = new DataView(buf, dataStart);
  const idx: Record<string, number> = {};
  props.forEach((p, i) => (idx[p] = i * 4));

  const positions = new Float32Array(n * 3);
  const colors = new Float32Array(n * 3);
  const scales = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const b = i * stride;
    positions[i * 3] = dv.getFloat32(b + idx["x"], true);
    positions[i * 3 + 1] = dv.getFloat32(b + idx["y"], true);
    positions[i * 3 + 2] = dv.getFloat32(b + idx["z"], true);
    colors[i * 3] = THREE.MathUtils.clamp(0.5 + SH_C0 * dv.getFloat32(b + idx["f_dc_0"], true), 0, 1);
    colors[i * 3 + 1] = THREE.MathUtils.clamp(0.5 + SH_C0 * dv.getFloat32(b + idx["f_dc_1"], true), 0, 1);
    colors[i * 3 + 2] = THREE.MathUtils.clamp(0.5 + SH_C0 * dv.getFloat32(b + idx["f_dc_2"], true), 0, 1);
    scales[i] = Math.max(
      Math.exp(dv.getFloat32(b + idx["scale_0"], true)),
      Math.exp(dv.getFloat32(b + idx["scale_1"], true)),
      Math.exp(dv.getFloat32(b + idx["scale_2"], true))
    );
  }
  return { count: n, positions, colors, scales };
}

/** Build a THREE.Points object from parsed splat data. */
export function buildSplatObject(splat: ParsedSplat, rendererHeight = 800): THREE.Points {
  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.BufferAttribute(splat.positions, 3));
  geo.setAttribute("aColor", new THREE.BufferAttribute(splat.colors, 3));
  geo.setAttribute("aScale", new THREE.BufferAttribute(splat.scales, 1));
  geo.computeBoundingSphere();

  const mat = new THREE.ShaderMaterial({
    transparent: true,
    depthWrite: false,
    uniforms: { uHeight: { value: rendererHeight } },
    vertexShader: /* glsl */ `
      attribute vec3 aColor; attribute float aScale;
      varying vec3 vColor;
      uniform float uHeight;
      void main() {
        vColor = aColor;
        vec4 mv = modelViewMatrix * vec4(position, 1.0);
        float px = aScale * uHeight / (-mv.z * 2.0 * tan(0.4363));
        gl_PointSize = max(1.0, px * 3.0);
        gl_Position = projectionMatrix * mv;
      }`,
    fragmentShader: /* glsl */ `
      varying vec3 vColor;
      void main() {
        float a = smoothstep(0.5, 0.12, length(gl_PointCoord - 0.5));
        if (a < 0.02) discard;
        gl_FragColor = vec4(vColor, a * 0.85);
      }`,
  });
  const points = new THREE.Points(geo, mat);
  points.frustumCulled = false;
  return points;
}

/** Fetch a .ply from public/splats/ and build it into a placeable object. */
export async function loadSplat(path: string, rendererHeight = 800): Promise<THREE.Points> {
  const res = await fetch(`${BASE}splats/${path}`);
  if (!res.ok) throw new Error(`Splat not found: public/splats/${path}`);
  const splat = parseSplatPLY(await res.arrayBuffer());
  const obj = buildSplatObject(splat, rendererHeight);
  obj.name = `splat:${path}`;
  return obj;
}
