/**
 * ashlane-world-loader.ts — Wires seeded 3D cities into the AshLane engine.
 *
 * Loads city JSON generated by tools/generative/world/city-3d.js
 * (via tools/generative/city-seed.js) and builds a real three.js level:
 * buildings with lit windows, neon signs, props, streetlights.
 *
 * Usage:
 *   import { loadSeededCity } from "./ashlane-world-loader";
 *   const city = await loadSeededCity("ashlane-01"); // fetches public/worlds/city-ashlane-01.json
 *   scene.add(city.group);
 *   city.dispose(); // when leaving the level
 *
 * Determinism: same seed string -> same JSON -> same level, every time.
 * Generate new levels with: node tools/generative/gen-city-proof.mjs <seed> public/worlds/
 */
import * as THREE from "three";

const BASE = import.meta.env.BASE_URL || "/";

export interface SeededCityJSON {
  meta: { generator: string; seed: string; version: number };
  size: { w: number; d: number; blockSize: number };
  buildings: Array<{ x: number; z: number; w: number; d: number; h: number; color: number }>;
  windows: Array<{ x: number; y: number; z: number; color: number; emissive: boolean }>;
  neons: Array<{ x: number; y: number; z: number; w: number; color: number }>;
  props: Array<{ kind: string; x: number; z: number; s: number; ry: number }>;
  streetlights: Array<{ x: number; z: number }>;
  streets: Array<{ id: string; axis: string; at: number; from: number; to: number; width: number }>;
  stats: Record<string, number>;
}

export interface SeededCity {
  group: THREE.Group;
  seed: string;
  stats: Record<string, number>;
  /** collision boxes for buildings: {min: Vector3, max: Vector3}[] */
  colliders: Array<{ min: THREE.Vector3; max: THREE.Vector3 }>;
  dispose(): void;
}

const PROP_COLORS: Record<string, number> = {
  dumpster: 0x1f5c2e, crate: 0x6b4a2a, barrel: 0x7a2a1e,
  hydrant: 0xb8b0a0, tree: 0x1e4423,
};

/** Fetch a pre-generated city JSON from public/worlds/. */
export async function fetchSeededCity(seed: string): Promise<SeededCityJSON> {
  const res = await fetch(`${BASE}worlds/city-${seed}.json`);
  if (!res.ok) throw new Error(`Seeded city not found for seed "${seed}" (looked in public/worlds/)`);
  return res.json();
}

/** Build a seeded city directly from JSON data (no fetch). */
export function buildSeededCity(data: SeededCityJSON, opts: { lightBudget?: number } = {}): SeededCity {
  const group = new THREE.Group();
  group.name = `seeded-city-${data.meta.seed}`;
  const colliders: Array<{ min: THREE.Vector3; max: THREE.Vector3 }> = [];
  const disposables: Array<{ dispose(): void }> = [];
  const lightBudget = opts.lightBudget ?? 24;
  let lightsUsed = 0;

  const mat = (c: number, extra = {}) => {
    const m = new THREE.MeshStandardMaterial({ color: c, roughness: 0.88, ...extra });
    disposables.push(m);
    return m;
  };

  const W = data.size.w, D = data.size.d;

  // Ground
  const groundGeo = new THREE.PlaneGeometry(W + 60, D + 60);
  const ground = new THREE.Mesh(groundGeo, mat(0x14161d, { roughness: 0.95 }));
  ground.rotation.x = -Math.PI / 2;
  ground.position.set(W / 2, 0, D / 2);
  ground.receiveShadow = true;
  group.add(ground);
  disposables.push(groundGeo);

  // Streets
  for (const s of data.streets) {
    const len = s.to - s.from;
    const g = new THREE.PlaneGeometry(s.axis === "z" ? s.width : len, s.axis === "z" ? len : s.width);
    const m = new THREE.Mesh(g, mat(0x1d2029, { roughness: 0.9 }));
    m.rotation.x = -Math.PI / 2;
    m.position.set(s.axis === "z" ? s.at : s.from + len / 2, 0.02, s.axis === "z" ? s.from + len / 2 : s.at);
    m.receiveShadow = true;
    group.add(m);
    disposables.push(g);
  }

  // Buildings (+ colliders for combat/movement)
  const boxGeo = new THREE.BoxGeometry(1, 1, 1);
  disposables.push(boxGeo);
  for (const b of data.buildings) {
    const m = new THREE.Mesh(boxGeo, mat(b.color));
    m.scale.set(b.w, b.h, b.d);
    m.position.set(b.x, b.h / 2, b.z);
    m.castShadow = true; m.receiveShadow = true;
    group.add(m);
    colliders.push({
      min: new THREE.Vector3(b.x - b.w / 2, 0, b.z - b.d / 2),
      max: new THREE.Vector3(b.x + b.w / 2, b.h, b.z + b.d / 2),
    });
    const cap = new THREE.Mesh(boxGeo, mat(0x101218));
    cap.scale.set(b.w + 0.6, 0.5, b.d + 0.6);
    cap.position.set(b.x, b.h + 0.25, b.z);
    group.add(cap);
  }

  // Windows (instanced planes, lit ones glow)
  const winGeo = new THREE.PlaneGeometry(1.6, 2.2);
  disposables.push(winGeo);
  const litMat = new THREE.MeshBasicMaterial({ color: 0xffd97a });
  const darkMat = new THREE.MeshBasicMaterial({ color: 0x11131c });
  disposables.push(litMat, darkMat);
  for (const w of data.windows) {
    const m = new THREE.Mesh(winGeo, w.emissive ? litMat : darkMat);
    m.position.set(w.x, w.y, w.z);
    group.add(m);
  }

  // Neon signs (emissive + capped point lights)
  for (const n of data.neons) {
    const g = new THREE.BoxGeometry(n.w, 1.1, 0.25);
    const neonMat = new THREE.MeshBasicMaterial({ color: n.color });
    const m = new THREE.Mesh(g, neonMat);
    m.position.set(n.x, n.y, n.z);
    group.add(m);
    disposables.push(g, neonMat);
    if (lightsUsed < lightBudget) {
      const glow = new THREE.PointLight(n.color, 30, 40, 1.8);
      glow.position.set(n.x, n.y, n.z + 2);
      group.add(glow);
      lightsUsed++;
    }
  }

  // Props
  for (const p of data.props) {
    let g: THREE.BufferGeometry;
    if (p.kind === "barrel") g = new THREE.CylinderGeometry(0.5 * p.s, 0.5 * p.s, 1.2 * p.s, 10);
    else if (p.kind === "tree") g = new THREE.ConeGeometry(1.6 * p.s, 4.5 * p.s, 8);
    else if (p.kind === "hydrant") g = new THREE.CylinderGeometry(0.3 * p.s, 0.35 * p.s, 1.1 * p.s, 8);
    else g = new THREE.BoxGeometry(1.6 * p.s, 1.1 * p.s, 1.0 * p.s);
    const m = new THREE.Mesh(g, mat(PROP_COLORS[p.kind] ?? 0x555555));
    const y = p.kind === "tree" ? 2.2 * p.s : (p.kind === "barrel" || p.kind === "hydrant" ? 0.6 * p.s : 0.55 * p.s);
    m.position.set(p.x, y, p.z);
    m.rotation.y = p.ry || 0;
    m.castShadow = true;
    group.add(m);
    disposables.push(g);
  }

  // Streetlights
  const poleGeo = new THREE.CylinderGeometry(0.12, 0.16, 9, 6);
  disposables.push(poleGeo);
  const poleMat = mat(0x2a2d36, { roughness: 0.7, metalness: 0.6 });
  let si = 0;
  for (const s of data.streetlights) {
    const pole = new THREE.Mesh(poleGeo, poleMat);
    pole.position.set(s.x, 4.5, s.z);
    group.add(pole);
    if (si++ % 8 === 0 && lightsUsed < lightBudget) {
      const lamp = new THREE.PointLight(0xffb45e, 60, 55, 1.9);
      lamp.position.set(s.x, 8.6, s.z);
      group.add(lamp);
      lightsUsed++;
    }
  }

  return {
    group,
    seed: data.meta.seed,
    stats: data.stats,
    colliders,
    dispose() {
      group.traverse(o => { /* geometries/materials tracked above */ });
      for (const d of disposables) d.dispose();
    },
  };
}

/** Convenience: fetch + build in one call. */
export async function loadSeededCity(seed: string, opts?: { lightBudget?: number }): Promise<SeededCity> {
  const data = await fetchSeededCity(seed);
  return buildSeededCity(data, opts);
}
