/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MocapRouteImport } from './routes/mocap'
import { Route as RagdollDemoRouteImport } from './routes/ragdoll-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MocapRoute = MocapRouteImport.update({
  id: '/mocap',
  path: '/mocap',
  getParentRoute: () => rootRouteImport,
} as any)
const RagdollDemoRoute = RagdollDemoRouteImport.update({
  id: '/ragdoll-demo',
  path: '/ragdoll-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mocap': typeof MocapRoute
  '/ragdoll-demo': typeof RagdollDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mocap': typeof MocapRoute
  '/ragdoll-demo': typeof RagdollDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mocap': typeof MocapRoute
  '/ragdoll-demo': typeof RagdollDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mocap' | '/ragdoll-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mocap' | '/ragdoll-demo'
  id: '__root__' | '/' | '/mocap' | '/ragdoll-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MocapRoute: typeof MocapRoute
  RagdollDemoRoute: typeof RagdollDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocap': {
      id: '/mocap'
      path: '/mocap'
      fullPath: '/mocap'
      preLoaderRoute: typeof MocapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ragdoll-demo': {
      id: '/ragdoll-demo'
      path: '/ragdoll-demo'
      fullPath: '/ragdoll-demo'
      preLoaderRoute: typeof RagdollDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MocapRoute: MocapRoute,
  RagdollDemoRoute: RagdollDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
